# 执行命令需要 sudo 命令
sudo: required

# Travis CI 预置了多种常用语言的配置，这里 Hexo 需要使用的是 Node.js
language: node_js

# 设置需要安装的 Node.js 版本号
node_js: "10"

script:
    - firebase deploy --non-interactive --project ${FIREBASE_PROJECT}  --token ${FIREBASE_TOKEN}