language: node_js
os: linux
dist: xenial
sudo: true
node_js: "10"
branches:
  only:
    - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
script:
    - firebase deploy --non-interactive --project ${FIREBASE_PROJECT}  --token ${FIREBASE_TOKEN}